# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_9.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1641, 924)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Users/JIRAPAT/new_python/logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"border:none;\n"
"background-color:transparent;\n"
"color:#fff;\n"
"}\n"
"#centralwidget{\n"
"background-color:#040f13;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.one = QtWidgets.QWidget(self.centralwidget)
        self.one.setMaximumSize(QtCore.QSize(400, 900))
        self.one.setStyleSheet("background-color:#071e26;\n"
"border-radius:20px;")
        self.one.setObjectName("one")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.one)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_one = QtWidgets.QWidget(self.one)
        self.widget_one.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_one.setObjectName("widget_one")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_one)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.laser = QtWidgets.QWidget(self.widget_one)
        self.laser.setMaximumSize(QtCore.QSize(16777215, 40))
        self.laser.setStyleSheet("background-color:#040f13;\n"
"border-radius: 20px;\n"
"\n"
"")
        self.laser.setObjectName("laser")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.laser)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_laser = QtWidgets.QLabel(self.laser)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_laser.setFont(font)
        self.label_laser.setObjectName("label_laser")
        self.horizontalLayout_11.addWidget(self.label_laser, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_8.addWidget(self.laser)
        self.widget_laser = QtWidgets.QWidget(self.widget_one)
        self.widget_laser.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_laser.setObjectName("widget_laser")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_laser)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.on = QtWidgets.QPushButton(self.widget_laser)
        self.on.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.on.setFont(font)
        self.on.setStyleSheet("#on{\n"
"background-color:#040f13;\n"
"border-radius: 50px;\n"
"border: 2px solid #fff;\n"
"}\n"
"#on:hover{\n"
"background-color:rgb(12, 52, 66);\n"
"border: 2px solid #608f47;\n"
"}\n"
"")
        self.on.setObjectName("on")
        self.horizontalLayout_12.addWidget(self.on)
        self.standby = QtWidgets.QPushButton(self.widget_laser)
        self.standby.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.standby.setFont(font)
        self.standby.setStyleSheet("#standby{\n"
"background-color:#040f13;\n"
"border-radius: 50px;\n"
"border: 2px solid #fff;\n"
"}\n"
"#standby:hover{\n"
"background-color:rgb(12, 52, 66);\n"
"border: 2px solid #9f9f00;\n"
"}\n"
"")
        self.standby.setObjectName("standby")
        self.horizontalLayout_12.addWidget(self.standby)
        self.off = QtWidgets.QPushButton(self.widget_laser)
        self.off.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.off.setFont(font)
        self.off.setStyleSheet("\n"
"#off{\n"
"background-color:#040f13;\n"
"border-radius: 50px;\n"
"border: 2px solid #fff;\n"
"}\n"
"\n"
"#off:hover{\n"
"background-color:rgb(12, 52, 66);\n"
"border: 2px solid #a60000;\n"
"\n"
"}\n"
"\n"
"")
        self.off.setObjectName("off")
        self.horizontalLayout_12.addWidget(self.off)
        self.verticalLayout_8.addWidget(self.widget_laser)
        self.verticalLayout_3.addWidget(self.widget_one)
        self.widget_massage = QtWidgets.QWidget(self.one)
        self.widget_massage.setMaximumSize(QtCore.QSize(16777215, 270))
        self.widget_massage.setStyleSheet("background-color:#040f13;\n"
"border-radius:20px;\n"
"\n"
"")
        self.widget_massage.setObjectName("widget_massage")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_massage)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_message = QtWidgets.QLabel(self.widget_massage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_message.setFont(font)
        self.label_message.setObjectName("label_message")
        self.verticalLayout_11.addWidget(self.label_message)
        self.massege = QtWidgets.QWidget(self.widget_massage)
        self.massege.setObjectName("massege")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.massege)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.text = QtWidgets.QTextBrowser(self.massege)
        self.text.setObjectName("text")
        self.verticalLayout_4.addWidget(self.text)
        self.verticalLayout_11.addWidget(self.massege)
        self.verticalLayout_3.addWidget(self.widget_massage)
        self.widget_3Dmodel = QtWidgets.QWidget(self.one)
        self.widget_3Dmodel.setMaximumSize(QtCore.QSize(16777215, 430))
        self.widget_3Dmodel.setStyleSheet("#widget_3Dmodel{\n"
"border: 1px solid #fff;\n"
"}\n"
"")
        self.widget_3Dmodel.setObjectName("widget_3Dmodel")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_3Dmodel)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.widget_3Dmodel)
        self.openGLWidget.setStyleSheet("")
        self.openGLWidget.setObjectName("openGLWidget")
        self.horizontalLayout_16.addWidget(self.openGLWidget)
        self.verticalLayout_3.addWidget(self.widget_3Dmodel)
        self.horizontalLayout.addWidget(self.one)
        self.two = QtWidgets.QWidget(self.centralwidget)
        self.two.setMaximumSize(QtCore.QSize(700, 900))
        self.two.setStyleSheet("\n"
"border-radius: 10px;")
        self.two.setObjectName("two")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.two)
        self.verticalLayout.setObjectName("verticalLayout")
        self.print_platform = QtWidgets.QWidget(self.two)
        self.print_platform.setMaximumSize(QtCore.QSize(16777215, 400))
        self.print_platform.setStyleSheet("background-color:#071e26;\n"
"border-radius:20px;")
        self.print_platform.setObjectName("print_platform")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.print_platform)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_print_platform = QtWidgets.QLabel(self.print_platform)
        self.label_print_platform.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_print_platform.setFont(font)
        self.label_print_platform.setObjectName("label_print_platform")
        self.verticalLayout_2.addWidget(self.label_print_platform)
        self.widget_print_platform_in = QtWidgets.QWidget(self.print_platform)
        self.widget_print_platform_in.setStyleSheet("background-color:#040f13;\n"
"border-radius:10px;\n"
"\n"
"")
        self.widget_print_platform_in.setObjectName("widget_print_platform_in")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_print_platform_in)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.in_speed_position = QtWidgets.QWidget(self.widget_print_platform_in)
        self.in_speed_position.setStyleSheet("")
        self.in_speed_position.setObjectName("in_speed_position")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.in_speed_position)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.speed_wg = QtWidgets.QWidget(self.in_speed_position)
        self.speed_wg.setMaximumSize(QtCore.QSize(260, 16777215))
        self.speed_wg.setStyleSheet("#speed_wg{\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"")
        self.speed_wg.setObjectName("speed_wg")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.speed_wg)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.set_speed = QtWidgets.QLabel(self.speed_wg)
        self.set_speed.setMaximumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.set_speed.setFont(font)
        self.set_speed.setStyleSheet("")
        self.set_speed.setObjectName("set_speed")
        self.horizontalLayout_15.addWidget(self.set_speed)
        self.lineEdit_speed = QtWidgets.QLineEdit(self.speed_wg)
        self.lineEdit_speed.setMaximumSize(QtCore.QSize(80, 40))
        self.lineEdit_speed.setStyleSheet("#lineEdit_speed{\n"
"background-color:#071e26;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#lineEdit_speed:hover{background-color:rgb(12, 52, 66);}")
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.horizontalLayout_15.addWidget(self.lineEdit_speed)
        self.down = QtWidgets.QPushButton(self.speed_wg)
        self.down.setMaximumSize(QtCore.QSize(40, 40))
        self.down.setStyleSheet("#down{\n"
"background-color:#071e26;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#down:hover{background-color:rgb(12, 52, 66);}")
        self.down.setObjectName("down")
        self.horizontalLayout_15.addWidget(self.down)
        self.up = QtWidgets.QPushButton(self.speed_wg)
        self.up.setMaximumSize(QtCore.QSize(40, 40))
        self.up.setStyleSheet("#up{\n"
"background-color:#071e26;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#up:hover{background-color:rgb(12, 52, 66);}")
        self.up.setObjectName("up")
        self.horizontalLayout_15.addWidget(self.up)
        self.horizontalLayout_3.addWidget(self.speed_wg)
        self.current_po = QtWidgets.QWidget(self.in_speed_position)
        self.current_po.setStyleSheet("#current_po{\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"")
        self.current_po.setObjectName("current_po")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.current_po)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.set_speed_2 = QtWidgets.QLabel(self.current_po)
        self.set_speed_2.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.set_speed_2.setFont(font)
        self.set_speed_2.setStyleSheet("")
        self.set_speed_2.setObjectName("set_speed_2")
        self.horizontalLayout_19.addWidget(self.set_speed_2)
        self.lineEdit_current_position = QtWidgets.QLineEdit(self.current_po)
        self.lineEdit_current_position.setMaximumSize(QtCore.QSize(80, 40))
        self.lineEdit_current_position.setStyleSheet("#lineEdit_current_position{\n"
"background-color:#071e26;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#lineEdit_current_position:hover{background-color:rgb(12, 52, 66);}")
        self.lineEdit_current_position.setObjectName("lineEdit_current_position")
        self.horizontalLayout_19.addWidget(self.lineEdit_current_position)
        self.set_value = QtWidgets.QPushButton(self.current_po)
        self.set_value.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.set_value.setFont(font)
        self.set_value.setStyleSheet("#set_value{\n"
"background-color:#071e26;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#set_value:hover{background-color:rgb(12, 52, 66);}")
        self.set_value.setObjectName("set_value")
        self.horizontalLayout_19.addWidget(self.set_value)
        self.horizontalLayout_3.addWidget(self.current_po)
        self.verticalLayout_9.addWidget(self.in_speed_position)
        self.widget_home = QtWidgets.QWidget(self.widget_print_platform_in)
        self.widget_home.setStyleSheet("")
        self.widget_home.setObjectName("widget_home")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_home)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.home = QtWidgets.QPushButton(self.widget_home)
        self.home.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.home.setFont(font)
        self.home.setStyleSheet("#home{\n"
"background-color:#071e26;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#home:hover{background-color:rgb(12, 52, 66);}")
        self.home.setObjectName("home")
        self.horizontalLayout_10.addWidget(self.home)
        self.get_current_position = QtWidgets.QPushButton(self.widget_home)
        self.get_current_position.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.get_current_position.setFont(font)
        self.get_current_position.setStyleSheet("#get_current_position{\n"
"background-color:#071e26;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#get_current_position:hover{background-color:rgb(12, 52, 66);}")
        self.get_current_position.setObjectName("get_current_position")
        self.horizontalLayout_10.addWidget(self.get_current_position)
        self.set_layer0 = QtWidgets.QPushButton(self.widget_home)
        self.set_layer0.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.set_layer0.setFont(font)
        self.set_layer0.setStyleSheet("#set_layer0{\n"
"background-color:#071e26;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#set_layer0:hover{background-color:rgb(12, 52, 66);}")
        self.set_layer0.setObjectName("set_layer0")
        self.horizontalLayout_10.addWidget(self.set_layer0)
        self.verticalLayout_9.addWidget(self.widget_home)
        self.verticalLayout_2.addWidget(self.widget_print_platform_in)
        self.verticalLayout.addWidget(self.print_platform)
        self.widget_G_Code = QtWidgets.QWidget(self.two)
        self.widget_G_Code.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_G_Code.setStyleSheet("background-color:#071e26;\n"
"border-radius:20px;")
        self.widget_G_Code.setObjectName("widget_G_Code")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_G_Code)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_Gcode = QtWidgets.QLabel(self.widget_G_Code)
        self.label_Gcode.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Gcode.setFont(font)
        self.label_Gcode.setObjectName("label_Gcode")
        self.verticalLayout_12.addWidget(self.label_Gcode)
        self.listWidget_gcode = QtWidgets.QListWidget(self.widget_G_Code)
        self.listWidget_gcode.setStyleSheet("background-color:#040f13;\n"
"border-radius:10px;\n"
"\n"
"")
        self.listWidget_gcode.setObjectName("listWidget_gcode")
        self.verticalLayout_12.addWidget(self.listWidget_gcode)
        self.verticalLayout.addWidget(self.widget_G_Code)
        self.gcodeStatus = QtWidgets.QWidget(self.two)
        self.gcodeStatus.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gcodeStatus.setObjectName("gcodeStatus")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gcodeStatus)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_GCodeStatus = QtWidgets.QLabel(self.gcodeStatus)
        self.label_GCodeStatus.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_GCodeStatus.setFont(font)
        self.label_GCodeStatus.setObjectName("label_GCodeStatus")
        self.horizontalLayout_2.addWidget(self.label_GCodeStatus)
        self.text_GCodeStatus = QtWidgets.QLabel(self.gcodeStatus)
        self.text_GCodeStatus.setText("")
        self.text_GCodeStatus.setObjectName("text_GCodeStatus")
        self.horizontalLayout_2.addWidget(self.text_GCodeStatus)
        self.verticalLayout.addWidget(self.gcodeStatus)
        self.widget_printing = QtWidgets.QWidget(self.two)
        self.widget_printing.setMaximumSize(QtCore.QSize(16777215, 105))
        self.widget_printing.setStyleSheet("")
        self.widget_printing.setObjectName("widget_printing")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_printing)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Load_G_Code = QtWidgets.QPushButton(self.widget_printing)
        self.Load_G_Code.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Load_G_Code.setFont(font)
        self.Load_G_Code.setMouseTracking(False)
        self.Load_G_Code.setStyleSheet("#Load_G_Code{\n"
"background:rgb(12, 52, 66);\n"
"border: 1px solid #fff;}\n"
"\n"
"#Load_G_Code:hover{background-color:#040f13;}")
        self.Load_G_Code.setCheckable(False)
        self.Load_G_Code.setAutoRepeat(False)
        self.Load_G_Code.setObjectName("Load_G_Code")
        self.horizontalLayout_13.addWidget(self.Load_G_Code)
        self.start_printing = QtWidgets.QPushButton(self.widget_printing)
        self.start_printing.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start_printing.setFont(font)
        self.start_printing.setStyleSheet("#start_printing{\n"
"background:rgb(12, 52, 66);\n"
"border: 1px solid #fff;}\n"
"\n"
"#start_printing:hover{background-color:#040f13;}")
        self.start_printing.setObjectName("start_printing")
        self.horizontalLayout_13.addWidget(self.start_printing)
        self.stop_printing = QtWidgets.QPushButton(self.widget_printing)
        self.stop_printing.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stop_printing.setFont(font)
        self.stop_printing.setStyleSheet("#stop_printing{\n"
"background:rgb(12, 52, 66);\n"
"border: 1px solid #fff;}\n"
"\n"
"#stop_printing:hover{background-color:#040f13;}")
        self.stop_printing.setObjectName("stop_printing")
        self.horizontalLayout_13.addWidget(self.stop_printing)
        self.verticalLayout.addWidget(self.widget_printing)
        self.widget_platform = QtWidgets.QWidget(self.two)
        self.widget_platform.setMaximumSize(QtCore.QSize(16777215, 380))
        self.widget_platform.setStyleSheet("background-color:#071e26;\n"
"border-radius:20px;")
        self.widget_platform.setObjectName("widget_platform")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_platform)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_platform_level = QtWidgets.QLabel(self.widget_platform)
        self.label_platform_level.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_platform_level.setFont(font)
        self.label_platform_level.setObjectName("label_platform_level")
        self.verticalLayout_7.addWidget(self.label_platform_level)
        self.listWidget_platform = QtWidgets.QListWidget(self.widget_platform)
        self.listWidget_platform.setStyleSheet("background-color:#040f13;\n"
"border-radius:10px;\n"
"\n"
"")
        self.listWidget_platform.setObjectName("listWidget_platform")
        self.verticalLayout_7.addWidget(self.listWidget_platform)
        self.verticalLayout.addWidget(self.widget_platform)
        self.horizontalLayout.addWidget(self.two)
        self.three = QtWidgets.QWidget(self.centralwidget)
        self.three.setMaximumSize(QtCore.QSize(500, 900))
        self.three.setStyleSheet("")
        self.three.setObjectName("three")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.three)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_parameter_2 = QtWidgets.QWidget(self.three)
        self.widget_parameter_2.setMaximumSize(QtCore.QSize(16777215, 800))
        self.widget_parameter_2.setStyleSheet("background-color:#071e26;\n"
"border-radius:20px;")
        self.widget_parameter_2.setObjectName("widget_parameter_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_parameter_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget = QtWidgets.QWidget(self.widget_parameter_2)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 15))
        self.widget.setObjectName("widget")
        self.verticalLayout_10.addWidget(self.widget)
        self.widget_parameter = QtWidgets.QWidget(self.widget_parameter_2)
        self.widget_parameter.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_parameter.setStyleSheet("#widget_parameter{\n"
"border: 1px solid #fff;\n"
"}\n"
"")
        self.widget_parameter.setObjectName("widget_parameter")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_parameter)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.parameter = QtWidgets.QLabel(self.widget_parameter)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.parameter.setFont(font)
        self.parameter.setStyleSheet("")
        self.parameter.setObjectName("parameter")
        self.verticalLayout_6.addWidget(self.parameter)
        self.verticalLayout_10.addWidget(self.widget_parameter, 0, QtCore.Qt.AlignHCenter)
        self.epfq = QtWidgets.QWidget(self.widget_parameter_2)
        self.epfq.setObjectName("epfq")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.epfq)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_epfq = QtWidgets.QLabel(self.epfq)
        self.label_epfq.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_epfq.setFont(font)
        self.label_epfq.setObjectName("label_epfq")
        self.horizontalLayout_5.addWidget(self.label_epfq, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_epfq = QtWidgets.QLineEdit(self.epfq)
        self.lineEdit_epfq.setMaximumSize(QtCore.QSize(150, 30))
        self.lineEdit_epfq.setStyleSheet("#lineEdit_epfq{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"}\n"
"#lineEdit_epfq:hover{background-color:rgb(12, 52, 66);}")
        self.lineEdit_epfq.setObjectName("lineEdit_epfq")
        self.horizontalLayout_5.addWidget(self.lineEdit_epfq)
        self.Set_epfq = QtWidgets.QPushButton(self.epfq)
        self.Set_epfq.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Set_epfq.setFont(font)
        self.Set_epfq.setStyleSheet("#Set_epfq{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#Set_epfq:hover{background-color:rgb(12, 52, 66);}")
        self.Set_epfq.setObjectName("Set_epfq")
        self.horizontalLayout_5.addWidget(self.Set_epfq)
        self.verticalLayout_10.addWidget(self.epfq)
        self.freq = QtWidgets.QWidget(self.widget_parameter_2)
        self.freq.setObjectName("freq")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.freq)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_freq = QtWidgets.QLabel(self.freq)
        self.label_freq.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_freq.setFont(font)
        self.label_freq.setObjectName("label_freq")
        self.horizontalLayout_6.addWidget(self.label_freq, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_freq = QtWidgets.QLineEdit(self.freq)
        self.lineEdit_freq.setMaximumSize(QtCore.QSize(150, 30))
        self.lineEdit_freq.setStyleSheet("#lineEdit_freq{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"}\n"
"#lineEdit_freq:hover{background-color:rgb(12, 52, 66);}")
        self.lineEdit_freq.setObjectName("lineEdit_freq")
        self.horizontalLayout_6.addWidget(self.lineEdit_freq)
        self.Set_freq = QtWidgets.QPushButton(self.freq)
        self.Set_freq.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Set_freq.setFont(font)
        self.Set_freq.setStyleSheet("#Set_freq{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#Set_freq:hover{background-color:rgb(12, 52, 66);}")
        self.Set_freq.setObjectName("Set_freq")
        self.horizontalLayout_6.addWidget(self.Set_freq)
        self.verticalLayout_10.addWidget(self.freq)
        self.offtime = QtWidgets.QWidget(self.widget_parameter_2)
        self.offtime.setObjectName("offtime")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.offtime)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_offtime = QtWidgets.QLabel(self.offtime)
        self.label_offtime.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_offtime.setFont(font)
        self.label_offtime.setObjectName("label_offtime")
        self.horizontalLayout_7.addWidget(self.label_offtime, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_offtime = QtWidgets.QLineEdit(self.offtime)
        self.lineEdit_offtime.setMaximumSize(QtCore.QSize(150, 30))
        self.lineEdit_offtime.setStyleSheet("#lineEdit_offtime{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"}\n"
"#lineEdit_offtime:hover{background-color:rgb(12, 52, 66);}")
        self.lineEdit_offtime.setObjectName("lineEdit_offtime")
        self.horizontalLayout_7.addWidget(self.lineEdit_offtime)
        self.Set_Offtime = QtWidgets.QPushButton(self.offtime)
        self.Set_Offtime.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Set_Offtime.setFont(font)
        self.Set_Offtime.setStyleSheet("#Set_Offtime{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#Set_Offtime:hover{background-color:rgb(12, 52, 66);}")
        self.Set_Offtime.setObjectName("Set_Offtime")
        self.horizontalLayout_7.addWidget(self.Set_Offtime)
        self.verticalLayout_10.addWidget(self.offtime)
        self.gateext = QtWidgets.QWidget(self.widget_parameter_2)
        self.gateext.setObjectName("gateext")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.gateext)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_gateext = QtWidgets.QLabel(self.gateext)
        self.label_gateext.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_gateext.setFont(font)
        self.label_gateext.setObjectName("label_gateext")
        self.horizontalLayout_8.addWidget(self.label_gateext, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_gateext = QtWidgets.QLineEdit(self.gateext)
        self.lineEdit_gateext.setMaximumSize(QtCore.QSize(150, 30))
        self.lineEdit_gateext.setStyleSheet("#lineEdit_gateext{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"}\n"
"#lineEdit_gateext:hover{background-color:rgb(12, 52, 66);}")
        self.lineEdit_gateext.setObjectName("lineEdit_gateext")
        self.horizontalLayout_8.addWidget(self.lineEdit_gateext)
        self.Set_gateext = QtWidgets.QPushButton(self.gateext)
        self.Set_gateext.setMaximumSize(QtCore.QSize(150, 30))
        self.Set_gateext.setStyleSheet("#Set_gateext{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#Set_gateext:hover{background-color:rgb(12, 52, 66);}")
        self.Set_gateext.setObjectName("Set_gateext")
        self.horizontalLayout_8.addWidget(self.Set_gateext)
        self.verticalLayout_10.addWidget(self.gateext)
        self.XY_Gain = QtWidgets.QWidget(self.widget_parameter_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.XY_Gain.setFont(font)
        self.XY_Gain.setObjectName("XY_Gain")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.XY_Gain)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_XY_Gain = QtWidgets.QLabel(self.XY_Gain)
        self.label_XY_Gain.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_XY_Gain.setFont(font)
        self.label_XY_Gain.setObjectName("label_XY_Gain")
        self.horizontalLayout_9.addWidget(self.label_XY_Gain, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_XY_Gain = QtWidgets.QLineEdit(self.XY_Gain)
        self.lineEdit_XY_Gain.setMaximumSize(QtCore.QSize(150, 30))
        self.lineEdit_XY_Gain.setStyleSheet("#lineEdit_XY_Gain{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"}\n"
"#lineEdit_XY_Gain:hover{background-color:rgb(12, 52, 66);}")
        self.lineEdit_XY_Gain.setObjectName("lineEdit_XY_Gain")
        self.horizontalLayout_9.addWidget(self.lineEdit_XY_Gain)
        self.Set_XY_Gain = QtWidgets.QPushButton(self.XY_Gain)
        self.Set_XY_Gain.setMaximumSize(QtCore.QSize(150, 30))
        self.Set_XY_Gain.setStyleSheet("#Set_XY_Gain{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#Set_XY_Gain:hover{background-color:rgb(12, 52, 66);}")
        self.Set_XY_Gain.setObjectName("Set_XY_Gain")
        self.horizontalLayout_9.addWidget(self.Set_XY_Gain)
        self.verticalLayout_10.addWidget(self.XY_Gain)
        self.mark_speed = QtWidgets.QWidget(self.widget_parameter_2)
        self.mark_speed.setObjectName("mark_speed")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.mark_speed)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_mark_speed = QtWidgets.QLabel(self.mark_speed)
        self.label_mark_speed.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mark_speed.setFont(font)
        self.label_mark_speed.setObjectName("label_mark_speed")
        self.horizontalLayout_18.addWidget(self.label_mark_speed, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_mark_speed = QtWidgets.QLineEdit(self.mark_speed)
        self.lineEdit_mark_speed.setMaximumSize(QtCore.QSize(150, 30))
        self.lineEdit_mark_speed.setStyleSheet("#lineEdit_mark_speed{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"}\n"
"#lineEdit_mark_speed:hover{background-color:rgb(12, 52, 66);}")
        self.lineEdit_mark_speed.setObjectName("lineEdit_mark_speed")
        self.horizontalLayout_18.addWidget(self.lineEdit_mark_speed)
        self.Set_mark_speed = QtWidgets.QPushButton(self.mark_speed)
        self.Set_mark_speed.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Set_mark_speed.setFont(font)
        self.Set_mark_speed.setStyleSheet("#Set_mark_speed{\n"
"background-color:#040f13;\n"
"border-radius:10px;\n"
"border: 1px solid rgb(82, 127, 122);\n"
"}\n"
"#Set_mark_speed:hover{background-color:rgb(12, 52, 66);}")
        self.Set_mark_speed.setObjectName("Set_mark_speed")
        self.horizontalLayout_18.addWidget(self.Set_mark_speed)
        self.verticalLayout_10.addWidget(self.mark_speed)
        self.widget_2 = QtWidgets.QWidget(self.widget_parameter_2)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_10.addWidget(self.widget_2)
        self.verticalLayout_5.addWidget(self.widget_parameter_2)
        self.widget_exit = QtWidgets.QWidget(self.three)
        self.widget_exit.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_exit.setObjectName("widget_exit")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_exit)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.exit_button = QtWidgets.QPushButton(self.widget_exit)
        self.exit_button.setMaximumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exit_button.setFont(font)
        self.exit_button.setStyleSheet("#exit_button{\n"
"background-color:#071e26;\n"
"border-radius:10px;\n"
"}\n"
"#exit_button:hover{background-color:rgb(12, 52, 66);}")
        self.exit_button.setCheckable(False)
        self.exit_button.setAutoRepeat(False)
        self.exit_button.setAutoRepeatDelay(300)
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_14.addWidget(self.exit_button, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.addWidget(self.widget_exit)
        self.horizontalLayout.addWidget(self.three)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.exit_button.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MTEC 3D PRINTER"))
        self.label_laser.setText(_translate("MainWindow", "L A S E R"))
        self.on.setText(_translate("MainWindow", "ON"))
        self.standby.setText(_translate("MainWindow", "STANDBY"))
        self.off.setText(_translate("MainWindow", "OFF"))
        self.label_message.setText(_translate("MainWindow", "Message"))
        self.label_print_platform.setText(_translate("MainWindow", "Print Platform"))
        self.set_speed.setText(_translate("MainWindow", "Speed"))
        self.down.setText(_translate("MainWindow", "-"))
        self.up.setText(_translate("MainWindow", "+"))
        self.set_speed_2.setText(_translate("MainWindow", "Current position :"))
        self.set_value.setText(_translate("MainWindow", "Set value"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.get_current_position.setText(_translate("MainWindow", "Get current position"))
        self.set_layer0.setText(_translate("MainWindow", "Set as first layer"))
        self.label_Gcode.setText(_translate("MainWindow", "G-Code"))
        self.label_GCodeStatus.setText(_translate("MainWindow", "G-Code Status : "))
        self.Load_G_Code.setText(_translate("MainWindow", "Load G-Code"))
        self.start_printing.setText(_translate("MainWindow", "Start printing"))
        self.stop_printing.setText(_translate("MainWindow", "Stop printing"))
        self.label_platform_level.setText(_translate("MainWindow", "Platform level"))
        self.parameter.setText(_translate("MainWindow", "    PARAMETER  SETTINGS   "))
        self.label_epfq.setText(_translate("MainWindow", "epfq :"))
        self.Set_epfq.setText(_translate("MainWindow", "Set epfq"))
        self.label_freq.setText(_translate("MainWindow", "freq :"))
        self.Set_freq.setText(_translate("MainWindow", "Set freq"))
        self.label_offtime.setText(_translate("MainWindow", "offtime :"))
        self.Set_Offtime.setText(_translate("MainWindow", "Set offtime"))
        self.label_gateext.setText(_translate("MainWindow", "gateext :"))
        self.Set_gateext.setText(_translate("MainWindow", "Set gateext"))
        self.label_XY_Gain.setText(_translate("MainWindow", "XY_Gain :"))
        self.Set_XY_Gain.setText(_translate("MainWindow", "Set XY_Gain"))
        self.label_mark_speed.setText(_translate("MainWindow", "mark speed :"))
        self.Set_mark_speed.setText(_translate("MainWindow", "Set mark speed"))
        self.exit_button.setText(_translate("MainWindow", "    EXIT PROGRAM    "))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
